language: php

php:
    - 5.6
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

branches:
    only:
        - master
        - develop

before_script:
    - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

install:
    - composer install

script: phpunit
